# -*- coding: utf-8 -*-
"""Python Basic Exercise for Beginners.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1khCoTL3LNKoqclOAwF2y5fxu5gHgVnF0

# **Exercise 1: Calculate the multiplication and sum of two numbers**
"""

num1=30
num2=40
sum=num1*num2
if sum<=1000:
    print(sum)
else:
  print("the sum is ",num1+num2)

"""# **Exercise 2: Print the sum of the current number and the previous number**"""

a=0

print("Current Number", 0,"Previous Number",0,"Sum:",0 )
for i in range(0,10):
  a=a+1
  print("Current Number", i,"Previous Number",a ,"Sum:",i+a )

#solution
previous=0
for i in range(1,11):
  sum=previous+i
  print("Current Number", i, "Previous Number ", previous, " Sum: ", sum)
  previous=i

"""# **Exercise 3: Print characters from a string that are present at an even index number**"""

a=input("enter word :")
print("ur word is :",a)

char=len(a)
for i in range(0,char-1,2):
  print(a[i])

"""# **Exercise 4: Remove first n characters from a string**"""

word=input("enter any word :")
WL=len(word)
n=int(input("remove characters from index must less than or equal to word lenght:"))
while n>WL :
  n=int(input("remove characters from index must less than or equal to word lenght:"))

print(word[n:])

"""# **Exercise 5: Check if the first and last number of a list is the same**"""

numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

a=numbers_x[0]
b=numbers_x[-1]
a2=numbers_y[0]
b2=numbers_y[-1]

if a==b:
  print("result is True")
else:
  print("result is false")

if a2==b2:
  print("result is True")
else:
  print("result is false")

"""# **Exercise 6: Display numbers divisible by 5 from a list**"""

li=[10, 20, 33, 46, 55]
wl=len(li)
for i in range (0,wl):
  a=li[i]%5
  
  if a==0:
    print(li[i])

#solution
li=[10, 20, 33, 46, 55]
for num in li:
  if num%5 ==0:
    print(num)

"""# **Exercise 7: Return the count of a given substring from a string**"""

sen="Emma is good developer. Emma is a writer Emma"
print(sen.count("Emma"))

"""# **Exercise 8: Print the following pattern**



"""

for i in range (6):
  for a in range(i):
    print(i,end=" ")
  print("\n")

"""# **Exercise 9: Check Palindrome Number**"""

num=input("enter any number :")
renum=num[::-1]
if int(num)==int(renum):
  print("Yes. given number is palindrome number")
else:
  print("No. given number is not palindrome number")

"""# **Exercise 10: Create a new list from a two list using the following condition**"""

list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
list1.extend(list2)
odd=[]
for number in list1:
  if number%2 == 1:
    odd.append(number)

print(odd)

"""# **Exercise 11: Write a Program to extract each digit from an integer in the reverse order.**"""

num="42335"
renum=num[::-1]
print(renum)

"""# **Exercise 12: Calculate income tax for the given income by adhering to the below rules**"""

def tax(income):
  if income<10000:
    pay="u dont need to pay"
  elif income<=20000:
    pay=1000
  else:
    remain=income-20000
    pay=remain/5+1000
  return pay


income=int(input("Enter ur income :"))
print(tax(income))